### ISSUE TITLE
can't see docker-compose file

### ISSUE THREAD

**Issue by shehackspurple** [isbang/compose-action#1]
Hi,

I'm trying to run your action and it can't see my docker-compose.yaml file. It's in the main directory, and I've tried "./docker-compose.yaml" and just "docker-compose.yaml", and it says it can't find it.

You can see more here: https://github.com/shehackspurple/Pixi/runs/1356370846?check_suite_focus=true

I think what's happening is it's looking in your github repo instead of mine...? Got any help for me on syntax?

My goal is to run the docker compose file, it runs the app, then I will run security tests on it.

![Screen Shot 2020-11-04 at 7 54 15 PM](https://user-images.githubusercontent.com/26744843/98195910-b34e7f00-1ed7-11eb-94d9-f0776f5fc6bc.png)
![Screen Shot 2020-11-04 at 7 53 55 PM](https://user-images.githubusercontent.com/26744843/98195916-b47fac00-1ed7-11eb-86d7-b4c96c1670af.png)

Thanks,
Tanya

**Comment by isbang** [comment]
My apologies for super late reply.

It's interesting. Because it works well in the folk version of your repository.

Please check below.
https://github.com/isbang/Pixi/runs/1464868632?check_suite_focus=true

**Comment by isbang** [comment]
I found a reason. This action need run `actions/checkout` before using. You should update your yaml file.

https://github.com/shehackspurple/Pixi/actions/runs/346784970/workflow#L35

Here is sample steps and thank you for using my action.
```yaml
  rundocker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: run-my-docker-compose
        uses: isbang/compose-action@v0.1.1 
        with: 
         compose-file: 'docker-compose.yaml'
```
