### ISSUE TITLE
node12 deprecated for actions

### ISSUE THREAD

**Issue by rpede** [isbang/compose-action#15]
Using `compose-action` result in following warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: isbang/compose-action, isbang/compose-action
```

I tested just changing to `node16` in action.yml. The warning goes away and I don't see anything breaking.

**Comment by rpede** [comment]
https://github.com/isbang/compose-action/pull/16

**Comment by isbang** [comment]
Thank you for your contribution :)

Could you please check if version v1.4.0 fixes this warning?

**Comment by rpede** [comment]
Our e2e pipeline using [v1.4.0](https://github.com/isbang/compose-action/releases/tag/v1.4.0) release just finished without the warning. I trust the release to be working as it should.

For reference, this is what I use in the workflow yml
```
      - uses: isbang/compose-action@v1.4.0
        with:
          compose-file: './docker-compose.ci.yml'
          down-flags: '--volumes'
```
So nothing fancy.

Thanks for the quick response. Much appreciated.
