### ISSUE TITLE
Cann't see logs from my enrtypoint - docker-compose runs with -d as default

### ISSUE THREAD

**Issue by nvwebm** [isbang/compose-action#17]
I'm trying to make a CI proccess to my Laravel application, I'm using docker-compose to run a test enviroment.

locally everthing works well, but when I tried to run it on Github action using `compose-action` I was unable to get it works:

The problem: I can't see the output from my `entrypoint.sh`

The solution I tried: add `--exit-code-from=web` to `up-flags` but then I got an error says `-d cannot be combined with --abort-on-container-exit or --attach-dependencies.`

What means the `docker-compose` command the package issuing runs with -d as default.

How do I know if my entrypoint even running (before I tried adding the above flag): I first got a permission denied error on trying to running my workflow

My docker-compose.yml

```version: '3.7'
services:
  web:
    image: composer:2.4
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - postgres
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=12345
      - DATABASE=testing
    depends_on:
      - mysql
    volumes:
      - ./:/app
    entrypoint:
      - '/app/entrypoint.sh' 

         
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=root
      - MARIADB_ROOT_PASSWORD=12345
      - MYSQL_DB=testing```

My workflow file:

```name: run server side tests on push
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  test-server-side:
    runs-on: ubuntu-latest
    env:
      COMPOSER_VERSION: 2
    steps:
      - name: checkout to current branch
        uses: actions/checkout@v3
      - name: Install Docker compose action  
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "docker-compose.yml"
          up-flags: "--exit-code-from=web"
     ```

My entrypoing.sh
```#!/bin/sh

install-php-extensions exif
composer install

php artisan key:generate

php artisan test```

Output from action with the flag:

```Run isbang/compose-action@v1.4.0
  with:
    compose-file: docker-compose.yml
    up-flags: --exit-code-from=web
  env:
    COMPOSER_VERSION: [2](https://github.com/nvwebm/landingMenus/actions/runs/3352294883/jobs/5554348030#step:3:2)
using --exit-code-from implies --abort-on-container-exit
-d cannot be combined with --abort-on-container-exit or --attach-dependencies.
Error: compose up failed {"exitCode":1,"err":"using --exit-code-from implies --abort-on-container-exit\n-d cannot be combined with --abort-on-container-exit or --attach-dependencies.\n","out":""}
```

Run without flag:

```Run isbang/compose-action@v1.4.0
  with:
    compose-file: docker-compose.yml
  env:
    COMPOSER_VERSION: [2]
Creating network "landingmenus_default" with the default driver
Pulling mysql (mariadb:latest)...
latest: Pulling from library/mariadb
...
...

Creating landingmenus_mysql_1 ... 
Creating landingmenus_mysql_1 ... done
Creating landingmenus_web_1   ... 
Creating landingmenus_web_1   ... done
compose started```

**Comment by isbang** [comment]
Could you please try this?
```yaml
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  test-server-side:
    runs-on: ubuntu-latest
    env:
      COMPOSER_VERSION: 2
    steps:
      - name: checkout to current branch
        uses: actions/checkout@v3
      - name: Install Docker compose action  
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "docker-compose.yml"
          up-flags: "--exit-code-from=web --abort-on-container-exit=web"
```

I found that if `--abort-on-container-exit` option exists then `-d` option is not default. But I have not tested yet.
https://github.com/PDMLab/docker-compose/blob/5c118476a2e1c9e567d622ea1a709e0ae8103d91/src/index.ts#L228-L253
