### ISSUE TITLE
Unable to use env variables

### ISSUE THREAD

**Issue by jkobus** [isbang/compose-action#25]
I get an error saying:

`The workflow is not valid. .github/workflows/tests.yaml (Line: 28, Col: 17): A mapping was not expected`

File:

```
name: "Tests"
on:
  pull_request:
  push:
    branches:
      - master
env:
  fail-fast: true

permissions:
  contents: read

jobs:
  test:
    name: "Testing"
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            docker-compose.yml
            docker-compose.override.yml
          down-flags: "--volumes"
          services: |
            php
          env:
            TEST: 1

      - name: PHP Unit
        if: always() && steps.install.outcome == 'success'
        run: docker compose exec php bin/phpunit
```
